version: '3.7'

services:
  backend:
    build:
      context: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: holiday
    volumes:
      - .:/holiday
    ports:
      - "8000:8000"